num = float(input("Enter a number: "))
word = input("Enter a word: ")
print("\nDemonstrating Built-in Functions:")
print(f"Absolute value of {num} is:", abs(num))
print(f"Rounded value of {num} is:", round(num))
print(f"{num} converted to integer is:", int(num))
print(f"Length of the word '{word}' is:", len(word))
print(f"The word '{word}' in uppercase is:", word.upper())
print(f"Minimum of digits in [3, 7, 1, 9]:", min(3, 7, 1, 9))
print(f"Maximum of digits in [3, 7, 1, 9]:", max(3, 7, 1, 9))
